version: '3.8'

services:
  sonata-playlists:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: sonata-playlists-microservice-image
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5005:5005"
    env_file:
      - test.env
    environment:
      # Used to download required dependencies from Suite module
      GITHUB_USERNAME: ${GH_USERNAME}
      GITHUB_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}

  db:
    image: 'postgres:15.2'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5