package com.odeyalo.sonata.playlists.service.generation;

import com.odeyalo.sonata.playlists.model.Playlist;
import com.odeyalo.sonata.playlists.model.PlaylistItem;
import org.jetbrains.annotations.NotNull;

import java.util.List;

/**
 * A meta that was auto-generated by Sonata
 * @param meta - generated meta info
 * @param tracks - tracks in this meta
 */
public record GeneratedPlaylist(
        @NotNull Playlist meta,
        @NotNull List<PlaylistItem> tracks
) { }
