package com.odeyalo.sonata.playlists.service.generation;

import com.odeyalo.sonata.playlists.model.PlayableItemType;
import com.odeyalo.sonata.playlists.model.Playlist;
import com.odeyalo.sonata.playlists.model.PlaylistItem;
import org.jetbrains.annotations.NotNull;

import java.util.List;

/**
 * A meta that was auto-generated by Sonata
 * @param meta - generated meta info
 * @param tracks - tracks in this meta
 * @param generatedFor - user id for which this playlist was generated
 */
public record GeneratedPlaylist(
        @NotNull Playlist meta,
        @NotNull List<Item> tracks,
        @NotNull String generatedFor
) {

    public record Item(
            @NotNull String id,
            @NotNull PlayableItemType type,
            int index
    ) {}
}
